/*MOSTRAR EL NOMBRE DE LA LINEA Y LA CANTIDAD DE PRODUCTOS POR CADA LINEA*/

SELECT L.NOMLINEA,
COUNT(*) AS CANTIDAD
FROM LINEAS L,
ARTICULOS A
WHERE L.CVELINEA = A.CVELINEA
GROUP BY L.NOMLINEA


/*DESPLEGAR EL NOMBRE DEL CLIENTES Y EL TOTAL FACTURADO POR CADA CLIENTES*/

SELECT C.NOMCLI, (SUBTOTAL+IVA)
FROM FACTURAS F, CLIENTES C
WHERE F.CVECLI=C.CVECLI
GROUP BY C.NOMCLI

/*MOSTRAR EL NOMBRE DEL DEPARTAMENTO Y EL SALARIO 
PROMEDIO OBTENIDO POR EMPLEADOS POR CADA DEPARTAMENTO*/

SELECT D.NOMDEPTO, AVG(E.SALARIO) AS SALARIO_PROMEDIO
FROM DEPARTAMENTOS D, EMPLEADOS E
WHERE D.CLAVEDEPTO = E.NUMDEPTO
GROUP BY D.NOMDEPTO;


/*MODIFICA EL ATERIOR COMANDO PARA EXCLUIR A LOS GERENTES*/

SELECT D.NOMDEPTO, AVG(E.SALARIO) AS SALARIO_PROMEDIO
FROM DEPARTAMENTOS D, EMPLEADOS E
WHERE D.CLAVEDEPTO = E.NUMDEPTO
  AND E.PUESTO != 'Gerente'
GROUP BY D.NOMDEPTO;

/*MOSTRAR EL NOMBRE DEL DEPARTAMENTO Y LA CANTIDAD DE PROYECTOS ASOCIADOS A EL*/

SELECT D.NOMDEPTO, COUNT(P.NUMPROY) AS CANTIDAD_PROYECTOS_ASOCIADOS
FROM DEPARTAMENTOS D, PROYECTOS P
WHERE D.CLAVEDEPTO = P.CLAVEDEPTO
GROUP BY D.NOMDEPTO;

/*MOSTRAR EL NOMBRE DEL DEPARTAMENTO CANTIDAD EMPLEADOS Y EL
 TOTAL DE HORAS HOMBRE; ASOCIADOS A CADA DEPARTAMENTO*/

SELECT  D.NOMDEPTO, 
COUNT(E.MATRICULA) AS CANTIDAD_EMPLEADOS, 
SUM(E.HORAS_HOMBRE) AS TOTAL_HORAS
FROM 
    DEPARTAMENTOS D, EMPLEADOS E
WHERE 
    D.CLAVEDEPTO = E.NUMDEPTO
GROUP BY 
    D.NOMDEPTO;
