/*MUETRS VALORES  O REPETIDOS DE EXISTENCIA*/

SELECT DISTINCT EXISTENCIAS
FROM ARTICULOS

/*USO DEL WHERE REQUIERE UNA COLUMNA O FORMULA 
COMPARADOR
DATO O FORMULA 
COMPARADORES
=
<
>
<>
<=
>=
*/

SELECT * 
FROM ARTICULOS

/* MOSTRAR LOS ARTICULOS CON EXISTENCIAS A MENOR DE 40*/
SELECT * 
FROM ARTICULOS
WHERE EXISTENCIAS < 40;

/* MOSTRAR LOS ARTICULOS CON EXISTENCIAS A MENOR DE 500*/
SELECT * 
FROM ARTICULOS
WHERE EXISTENCIAS > 500;


/*DESPLEGAR SUS FACTURAS CUYO MONTO TOTAL DE SUBTOATL+IVA< 1000*/

SELECT * 
FROM FACTURAS
WHERE SUBTOTAL+IVA > 1000;


/*MOSTRAR LAS PARTIDAS EN LAS CUALES EL IMPORTE SEA MAYOR 1000. EL IMPORTE ES 
EL PRODUCTO DEL PRECIO DE VENTA POR LA CANTIDAD*/
SELECT *
FROM partidas
WHERE (PVENTA* CANTIDAD) > 1000;


/*ORDENAR LOS ANTERIORES DATOS  CONFORME AL PRECIO DE VENTA DESCEDENTE*/

SELECT *
FROM partidas
WHERE (PVENTA * cantidad) > 1000
ORDER BY PVENTA DESC;

/*MOSTRAR LOS CLIENTES CUYA CABLE SEA MAYOR A 600*/

SELECT *
FROM clientes
WHERE CVECLI > 600;

/*DESPLEGAR LLS clientes CUYO CODIFO SEA MENOR A 500 PERO SOLO MOSTRANDO LOS NOMBRES*/
SELECT NOMCLI
FROM clientes
WHERE CVECLI < 500;

/*DESPLEGAR LOS CLIENTES CUYO CODIDO SEA MAYOR O IGUAL A 500 Y SEA MENOR IGUA A 600*/
SELECT *
FROM clientes
WHERE CVECLI >=500
AND CVECLI >= 500

/*CAMBIARLE LA FECHA */
UPDATE facturas SET FECHA = CURRENT_DATE;

/*MOSTRAR LAS LINEAS CUYO CODIGO ES MENOR A 300 O BIEN CUYA LINEA SEA ELECTRONICA*/

SELECT *
FROM LINEAS
WHERE CVELINEA < 300
OR NOMLINEA= 'ELECTRONICA'


/*DONDE LA CLAVE DE LIENA ESTE ENTRE 300 O 400 MIENTRAS LA LINEA SEA 400*/
SELECT *
FROM LINEAS
WHERE (CVLINEA >=300
AND CVELINEA <= 400)
OR NOMLINEA = 'ELECTRONICA'


/*DESPLEGAR LOS ARTICULOS CUYO PRECIO SEA DIFERENTE DE 250*/
SELECT * FROM ARTICULOS
WHERE NOT PRECIO = 250