SELECT* FROM articulos 
where Cveart in (253,354,455,501,652);

SELECT* FROM articulos 
where Cveart = 253
or
CVEART = 354
OR
CVEART = 455
OR
CVEART = 501
OR
CVEART = 652;


/*MOSTRAR LA LINEAS COMO CODIGO IGUAL QUE LOS ANTERIORES*/







/*MOSTRAR LOS SIGUIENTES DATOS QUE ES: ESTUFA, CAMISA, SHORT, PERFUME, TOMATE*/

SELECT articulos FROM Productos WHERE nombre IN ('Estufa', 'Camisa', 'Short', 'Perfume', 'Tomate');



/*MOSTRA LOS DATOS :PANTALON, MARTILLO, SALCHICHA*/

SELECT articulos
FROM NOMBRE
WHERE NOMBRE IN ('Pantalon', 'Martillo', 'Salchicha');

/*PARA BUSCAR PATRONES SE USA EL LIKE


CON LOS SIGUIENTES OPCIONES 

%= EL TEXTO QUE SEA 
_=CUALQUIER COSA EN ESA POSICION/*



/*QUE EMPIEZE CON PAN*/
SELECT * FROM articulos
WHERE NOMBRE LIKE 'PAN%'

/* DESPLEGAR ARTICULOS CUYO NOMBRE TERMINE CON S*/
SELECT * FROM articulos
WHERE NOMBRE LIKE '%S'

/*MOSTRA LOS articulos CUYO NOMBRE APAREZCA UNA ESPANTOSA X*/
SELECT * FROM articulos
WHERE NOMBRE LIKE '%X%'

SELECT * FROM articulos
WHERE NOMBRE LIKE '%AN%'


/*TRAEME LOS articulos DE LA 3 LETRA TENGAN UNA N SIN IMPORTAR LOS DEMAS*/
SELECT * FROM articulos
WHERE NOMBRE LIKE '_N%'



/*MODIFICAR EL COMANDO PARA QUE ADEMAS EN LA 5 POSICION LLEVE UNA A*/
SELECT * FROM articulos
WHERE NOMBRE LIKE '____A%'


/*CLIENTES QUE TENGAN UNA Z EN SUS NOMBRES*/

SELECT * FROM CLIENTES
WHERE NOMCLI LIKE '%Z%'




