SELECT NUMDEPTO, COUNT(*)
FROM EMPLEADOS
WHERE GENERO='M'
GROUP BY NUMDEPTO


SELECT COUNT(*),NUMPROYSUP
FROM PROYECTOS
GROUP BY NUMPROYSUP

/*AGRUPA*/
SELECT COUNT(*), CLAVEDEPTO
FROM PROYECTOS
WHERE NOMPROY LIKE '%LINEA DE SOLDADURA%'
GROUP BY CLAVEDEPTO

SELECT CVELINEA, COUNT(*)
FROM ARTICULOS 
GROUP BY CVELINEA

/*CUANTAS FACTURAS SEA ENMITIDO POR CADA CLIENTES*/
SELECT CVECLI, COUNT(*)
FROM FACTURAS 
GROUP BY CVECLI


/*HAVING*/
SELECT CVECLI, COUNT(*)
FROM FACTURAS 
GROUP BY CVECLI
HAVING COUNT(*)>5

/*MOSTRAR EL TOTAL DE LO FACTURADO POR EL CLIENTE SIEMPRE Y CUANDO SEAN MENOR DE 10 FACTURAS*/
SELECT SUM(SUBTOTAL+IVA),CVECLI
FROM FACTURAS 
GROUP BY CVECLI
HAVING COUNT(*)< 10

/*DESPLEGAR LA SUMA DE LAS EXISTENCIAS DE ARTICULOS POR CADA LINEA SIEMPRE QUE 
LA LINEA TENGA MENOS DE 3 ARTICULOS*/

SELECT SUM(EXISTENCIAS),CVELINEA
FROM ARTICULOS
GROUPBY CVELINEA
HAVING COUNT(*)< 3

SELECT L.NOMLINEA, A.NOMLINEA
FROM ARTICULOS A, LINEAS L
WHERE A.CVELINEA = L.CVELINEA

/*MOSRAR EL FOLIO Y LA FECHA DE FACTURAS ADEMAS DEL NOMBRE DEL CLIENTE*/

SELECT F.FOLIO, F.FECHA, C.NOMCLI
FROM FACTURAS F, CLIENTES C
WHERE F.CVECLI = C.CVECLI

/*MODIFICA EL ANTERIOR PARA MOSTRAR SOLO LA DE CLIENTE DE YOLANDA SALDIVAR*/
SELECT F.FOLIO, F.FECHA, C.NOMCLI
FROM FACTURAS F, CLIENTES C
WHERE F.CVECLI = C.CVECLI
AND C.NOMBRE='YOLANDA SALDIVAR'

--EJERICIO DE AYER
SELECT A.NOMBRE,P.PVENTA * P.CANTIDAD
FROM FACTURAS F, CLIENTES C, PARTIDAS P,
ARTICULOS A
WHERE F.CVECLI = C.CVECLI
AND F.FOLIO = P.FOLIO
AND P.CVEART = A.CVEART
