/*4*/

SELECT E.NOMBRE, E.NIVELEST
FROM EMPLEADOS E, DEPARTAMENTOS D
WHERE E.NUMDEPTO = D.CLAVEDEPTO
  AND D.NOMDEPTO = 'PRODUCCION DE SISTEMAS';


/*5*/  
SELECT E.APELLIDO, E.PUESTO, D.NOMDEPTO
FROM EMPLEADOS E, DEPARTAMENTOS D
WHERE E.NUMDEPTO = D.CLAVEDEPTO
  AND D.NOMDEPTO LIKE '%PLAN%';


/*6*/
SELECT COUNT(P.NUMPROY) AS CANTIDAD_DE_PROYECTOS
FROM PROYECTOS P, DEPARTAMENTOS D
WHERE P.CLAVEDEPTO = D.CLAVEDEPTO
  AND D.NOMDEPTO = 'PLANIFICACION';