/*SINTAXIS DEL COMANDO*/

SELECT//DATOS Y/O INFORMACION 

FROM // DE QUE TABLA(S) VIENEN LOS DATOS O LA INFORMACION

WHERE //BAJO QUE CONDICIONES

GROUP BY// MEDIANTE AGRUPACIONES

HAVING// SEIMPRE QUE CUMPLAN CIERTA CONDICIONES

UNION// UNIDO A OTRO COMANDO(S) SELECT

ORDER BY//ORDENADOS CONFORME A 

]
[ ESTAS SON OPCIONLES