/*REDUCIR EN 1 LAS EXISTENCIAS DE TODOS LOS ARTICULOS 
*/
UPDATE articulos
SET existencias = existencias - 1;



/*AUMENTAR EL PRECIO DE UN 10% DEL ROLLO DE LIMON
*/
UPDATE articulos
SET precio = precio * 1.10
WHERE NOMBRE = 'rollo de limon';


/* TORTAS CAMBIARLE EL NOMBRE A TORTAS DE JAMON
*/
UPDATE articulos
SET nombre = 'tortas de jamon'
WHERE nombre = 'tortas';


/*PONER EL IVA CORRECTO CONFORME AL PRECIO DE LOS ARTICULOS EN FACTURAS
*/
UPDATE FACTURAS
SET IVA = SUBTOTAL * 0.16




/*INCREMENTAR EN UN 15% EL PRECIO DE VENTA Y LA CANTIDAD DISMINUIRLA EN 10 PARA EL ARTICULO 2 EN LA PARTIDADS
*/

UPDATE PARTIDAS
SET PVENTA = PVENTA * 1.15,
CANTIDAD = CANTIDAD -1
WHERE CVEART = 802



/*CORREGIR LOS ERRORES DE NOE*/

UPDATE facturas SET `CVECLI` = '301' WHERE `facturas`.`FOLIO` = 301;

UPDATE facturas SET `CVECLI` = '302' WHERE `facturas`.`FOLIO` = 302;

UPDATE facturas SET `CVECLI` = '303' WHERE `facturas`.`FOLIO` = 303;

UPDATE facturas SET `CVECLI` = '304' WHERE `facturas`.`FOLIO` = 304;

UPDATE facturas SET `CVECLI` = '305' WHERE `facturas`.`FOLIO` = 305;


/*ESTABLECER LA FECHA DE HOY PARA TODAS LA FACTURAS*/

UPDATE FACTURAS SET FECHA = CURRENT_DATE();


/*AGREGAR LA COLUMNA COSTO DE TIPO DECIMAL 8,2 A LA TABLA DE ARTICULOS . LUEGO ASIGNAR AL COSTO EL 70% DEL VALOR*/
 ALTER TABLE ARTICULOS
 ADD COSTO DECIMAL (8,2);

ALTER TABLE articulos ADD COSTOS DECIMAL(8,2) NOT NULL AFTER CVELINEA;

UPDATE articulos
SET COSTO = PRECIO * 0.70



/*BORRAR TODOS LOS ARTICULOS QUE SEAN MENOR DE 10*/
UPDATE articulos
WHERE EXISTENCIA < 10;



/*incremenTaR en un 5% los precios de los articulos que tenga 14 unidades existencias y su precio menor a 200*/


UPDATE articulos
SET precio = precio * 1.05
WHERE EXISTENCIA = 14
AND precio < 200;

/*ELIMINAR LAS FACTURAS QUE LA SUMA DE LOS SUBTOTAL MAS EL IVA SEA MENOR  A 400*/

DELETE FROM FACTURAS
WHERE SUBTOTAL + IVA < 400;


/*LA TABLA LINEAS VA TENER UN CAMPO NUEVO(ARTICULOS_SMALLINT)*/

ALTER TABLE lineas
ADD COLUMN articulos SMALLINT;

/*ASIGANR 10 ARTICULOS A TODAS LA LINEAS*/

UPDATE lineas
SET articulos = 10;


/*INCREMENTRA EN 5 ARTICULOS LAS LINEAS CUYA CLAVE SEA MENOR A 400*/

UPDATE lineas
SET articulos = articulos + 5
WHERE CVELINEA < 400;

/*eliminar las lineas cuya clave sea mayor 800*/

DELETE FROM lineas
WHERE CVELINEA > 800;


/*AGREGAR 3 DIRRECIONES DE LA TABLA CLIENTES Y ELIMINAR 3 DIRECCIONES*/
DELETE FROM clientes
WHERE DIR IN ('Palma Real', 'Laguna Real', 'Colonia Amapolas');

INSERT INTO clientes (CVECLI,NOMCLI,DIR,RFC)
values ('803', 'leonardo vidal chapol','francisco imadero','e8176391nsh1827');

INSERT INTO clientes (CVECLI,NOMCLI,DIR,RFC)
values ('804', 'guzman sanchez','xalapa','e8176391nsh18267');

INSERT INTO clientes (CVECLI,NOMCLI,DIR,RFC)
values ('805', 'mendoza hernandez','ortiz rubio sur','e8176391nsh18223');

INSERT INTO clientes (DIR)
VALUES ('CARMEN LAGUNES'),
       ('MISANTLA'),
       ('CHAPOLUNA'),
       ('SAN JUAN DEL CARMEN');
